### PR TITLE
EPMLSTRCMW-179: inactive user is able to sign in

### PR DESCRIPTION
**Pull request by OstapStrashevskii**
Forbid the inactive user to sign in

### CODE REVIEW

**Review by GrigoriiBerezin — APPROVED** [review]
Perfect

**Review by iliaonishchenko — CHANGES_REQUESTED** [review]
Looks like there are merge conflicts..

**Review by Dmitrii-Shevchenko — APPROVED** [review]
Great work!

**Review by iliaonishchenko — APPROVED** [review]

**Review by myazinn — APPROVED** [review]
LGTM

**Pull request merged**
