### PR TITLE
Epmlstrcmw 132: Create CRUD methods for project entity

### PR DESCRIPTION
**Pull request by nikita0levchenko**
Implemented methods getProjectByName, addProject, decativateProjectById, updateProject for entity "project", and test's for them

### CODE REVIEW

**Comment by myazinn** [comment]
1) Give this PR a more appropriate name. If it is a placeholder, why do we need to merge it? It may seem like a placeholder to you, but if someone will open a history of all merged PR's, he will never understand why this PR called a placeholder. 
2) We don't use links to jira here. Technically this is an open source project, which means anyone outside of the epam may participate. He will be very upset if he won't be able to understand what is going on using this links.
3) Review from other students ALWAYS comes before mentor's review.

**Comment by ilyaonishenko** [comment]
@myazinn
This particular request contains 2 branches which have already been reviewed and approved by students and mentors. Also there are no conflicts with develop so I told Nikita that process should not contain review at all. I guess it’s why he asked only for mentors review.

**Comment by nikita0levchenko** [comment]
@myazinn
Yes, this code already was reviewed by you and another mentors

**Comment by myazinn** [comment]
@ilyaonishenko 
But it does require a review :) A lot of things have changed since we approved the first branch.
@GrigoriiBerezin found an [issue ](https://github.com/EpamLifeSciencesTeam/cmwl_pipeline/pull/56#discussion_r402559915)with the formatting of the `import` statements. Take a look at the `ProjectServiceTest`, it still contains the same problems.
Also, look at `ProjectControllerItTest`. It performs the initializations of the containers outside the `beforeAll` method. At the time this branch was approved, such initialization was done everywhere. But then it was fixed [here](https://github.com/EpamLifeSciencesTeam/cmwl_pipeline/pull/40). Therefore, I believe that similar changes should be made in this PR.
I don't know how many things are also changed. Maybe that's all, maybe there are other things.

**Comment by nikita0levchenko** [comment]
@myazinn 
Problems with formatting import statements and containers in ProjectControllerItTest was fixed.

**Comment by ilyaonishenko** [comment]
@myazinn ok, sounds reasonable. Let's do the review :)

**Comment by nikita0levchenko** [comment]
@myazinn
Name and description of PR was changed

**Comment by ilyaonishenko** [comment]
@nikita0levchenko the MR name should be a bit more descriptive


@OstapStrashevskii @AndreiMaksimenko @IaroslavTavchenkov @GrigoriiBerezin any comments guys?

**Comment by GrigoriiBerezin** [comment]
@ilyaonishenko Do you mean that "Project feature" description dosn't say actual information about MR?

**Comment by ilyaonishenko** [comment]
@GrigoriiBerezin yes. It doesn't describe anything about this MR.

**Comment by nikita0levchenko** [comment]
@ilyaonishenko 
Fixed a name

**Comment by ilyaonishenko** [comment]
That's better. But "Project feature" is redundant. We can see that it's feature and it's about project from the second sentence.

**Comment by ilyaonishenko** [comment]
@nikita0levchenko I guess you're not using git hooks we've developed for this project. 
Some of your commit messages don't follow the notation. 
Please fix it.

**Pull request merged**
