### PR TITLE
test: initialize mock server once per testset

### PR DESCRIPTION
**Pull request by GrigoriiBerezin**
Adds to 136 task about implementation HttpClient.
Initialize mock server once per testset for passing tests in Travis

### CODE REVIEW

**Review by AndreiMaksimenko — APPROVED** [review]
Looks good. May be to use the more useful name of HttpClient instead client.

**Comment by IaroslavTavchenkov** [comment]
Seems nice!)

**Review by IaroslavTavchenkov — APPROVED** [review]

**Review by Dmitrii-Shevchenko — APPROVED** [review]
Good work!

**Review by mnesvit — APPROVED** [review]

**Review by iliaonishchenko — APPROVED** [review]
Nice!

**Comment by ilyaonishenko** [comment]
@GrigoriiBerezin please use more appropriate branch naming next time.

**Pull request merged**
