### PR TITLE
EPMLSTRCMW-178 Fix GitLab issue with body content type

### PR DESCRIPTION
**Pull request by GrigoriiBerezin**

### CODE REVIEW

**Review by IaroslavTavchenkov — APPROVED** [review]
Well done, Sherlock! :)

**Review by Dmitrii-Shevchenko — APPROVED** [review]
Brilliantly!

**Review by OstapStrashevskii — APPROVED** [review]
Good job!

**Review by iliaonishchenko — APPROVED** [review]
Looks good to me.

**Review by myazinn — APPROVED** [review]
LGTM

**Pull request merged**
