### PR TITLE
EPMLSTRCMW-241 refactor: Split Service classes into trait and its implementation

### PR DESCRIPTION
**Pull request by Nikolai-Isaev**
refactor: Split service classes to trait and implementation

### CODE REVIEW

**Review by DruzhininPavel — APPROVED** [review]
Yep/ Looks good.

**Review by OlegKoshelev — APPROVED** [review]
Good work

**Review by myazinn — CHANGES_REQUESTED** [review]
What about `AggregationService`?

**Comment by Nikolai-Isaev** [comment]
AggregationService added

**Review by myazinn — APPROVED** [review]

**Review by gominasian — APPROVED** [review]

**Review by Dmitrii-Shevchenko — APPROVED** [review]

**Pull request merged**
